### ISSUE TITLE
first release todo list

### ISSUE THREAD

**Issue by shin4488** [shin4488/no1-company-share#23]
* [x] #11 カード画面
* [x] サーバからapiレスポンス
* [x] urlからメタ画像取得
* [x] urlからメタ画像取得リクエスト内のURLチェック
* [x] ローディング
* [x] lazy loading → さらにn件表示
* [x] 新規ボタン固定
* [x] モーダル開閉
* [x] #24
* [x] 会社検索
* [x] 一位内容追加削除
* [x] 「はい/いいえ」の確認ダイアログ
* [x] #27 初期処理で区分値マスタ取得
* [x] #27 ユーザマスタ登録
* [x] #27 会社マスタ登録ロジッククラス
* [x] #29 未ログイン時に投稿追加ボタン・通報ボタン非表示
* [x] #29
* [x] #29 投稿編集、更新
* [x] #29 会社名取得時に英語名と日本語名を別々で取得、会社マスタ登録時に日本語名と英語名を別々で登録
* [x] #30
* [x] #32
* [x] #34 お気に入り画面遷移
* [x] #32 マイ投稿画面遷移
* [x] #34 投稿削除
* [x] #34 お気に入り登録、削除
* [x] #34 通報登録画面
* [x] ケータイ画面サイズで、下バーのアクティブ制御
* [x] さらに表示/非表示
* [x] #37 「アプリの使い方」メニュー追加
* [x] 入力時のフロント側でのエラーメッセージ表示
* [x] スピナーをモーダルダイアログよりも上に表示
* [x] favicon・title・OG
* [x] #39
